title: Subjectivité de L'Objectif
description: > # this means to ignore newlines until "baseurl:"
  Travel photography blog.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://acrosszuniverse.com" # the base hostname & protocol for your site, e.g. http://example.com

# Comments
disqus_identifier: subjectivite-de-lobjectif # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

sass:
  sass_dir: assets/css/sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include:
 - _pages

exclude:
  - assets/css/sass
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - yarn.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - scripts
  - Dockerfile
  - docker-compose
  - .travis.yml
